ARG ACCOUNT_NUMBER
FROM $ACCOUNT_NUMBER.dkr.ecr.eu-west-2.amazonaws.com/yara:latest
WORKDIR /rules
COPY rule-sources /rules/rule-sources
COPY compile.py /rules/compile.py
RUN apk update && apk add git python3-dev && \
            pip3 install yara-python && \
            cat rule-sources | xargs -n1 git clone && \
            ./compile.py